### ISSUE TITLE
A dokuwiki upgrade resulted in a php error

### ISSUE THREAD

**Issue by aw-systems** [splitbrain/dokuwiki-plugin-upgrade#91] opened 2015-09-29 07:33 UTC
issue: require_once(): Failed opening required require_once(/usr/share/nginx/www/dokuwiki/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/www/dokuwiki/inc/init.php on line 194

actions that caused the error:

manual installation of dokuwiki (end 2014)
use of dokuwiki with own template
installing of upgrade plugin (dokuwiki version difference of 3 versions including bugfix versions )
giving write permission for plugin in dokuwiki directory including dokuwiki root directory
clicking "Continue" after everything was ok
upgrade plugin creates directory vendor in dokuwiki root folder
after upgrade folder "vendor" is not in directory (assumed deletion by upgrade plugin)
opening dokuwiki with browser throws php error

reproducable: unknown

complete error message:

2015/09/29 07:08:05 [error] 2635#0: *1022 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/usr/share/nginx/www/dokuwiki/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/www/dokuwiki/inc/init.php on line 194
PHP message: PHP Fatal error:  require_once(): Failed opening required '/usr/share/nginx/www/dokuwiki/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/nginx/www/dokuwiki/inc/init.php on line 194" while reading response header from upstream, client: 192.168.2.50, server: localhost, request: "GET /dokuwiki/doku.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.2.75"

**Comment by splitbrain** [comment] 2015-09-29 14:01
I can not reproduce this and there's nothing in the code that would delete the vendor directory.

How exactly was DokuWiki set up in the first place. The forum thread you posted to mentions symlinks to other places... was that the case for you too?

**Comment by aw-systems** [comment] 2015-09-29 14:45
I'm investigating the problem further . I assume a problem with file permissions. Concerning symlinks:

the command ( a small L at the end) "find dokuwiki -type l" finds nothing. The output of diff:

 diff -r dokuwiki/ /root/dokuwiki-2015-08-10a/ | grep "Only in" | grep -v "dokuwiki/data"
Only in dokuwiki/conf: acl.auth.php
Only in dokuwiki/conf: local.php
Only in dokuwiki/conf: local.php.bak
Only in dokuwiki/conf: plugins.local.php
Only in dokuwiki/conf: plugins.local.php.bak
Only in dokuwiki/conf: users.auth.php
Only in dokuwiki/inc: geshi
Only in /root/dokuwiki-2015-08-10a/: install.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authad/lang/lv: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authldap/lang/lv: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authmysql/lang/fi: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authmysql/lang/lv: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authpgsql/lang/it: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authpgsql/lang/lv: settings.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/authpgsql/lang/pl: settings.php
Only in dokuwiki/lib/plugins: function
Only in /root/dokuwiki-2015-08-10a/lib/plugins/popularity/lang/hr: lang.php
Only in /root/dokuwiki-2015-08-10a/lib/plugins/revert/lang/hr: lang.php
Only in dokuwiki/lib/plugins: upgrade
Only in /root/dokuwiki-2015-08-10a/lib/plugins/usermanager/lang/hr: lang.php
Only in dokuwiki/lib/tpl: 20cones
Only in /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki: lang
Only in dokuwiki/lib/tpl: wwiki
Only in /root/dokuwiki-2015-08-10a/: vendor

and the files with a diff ("diff -r dokuwiki/ /root/dokuwiki-2015-08-10a/ | grep "diff -r" "):

diff -r dokuwiki/inc/init.php /root/dokuwiki-2015-08-10a/inc/init.php
diff -r dokuwiki/lib/scripts/compatibility.js /root/dokuwiki-2015-08-10a/lib/scripts/compatibility.js
diff -r dokuwiki/lib/scripts/editor.js /root/dokuwiki-2015-08-10a/lib/scripts/editor.js
diff -r dokuwiki/lib/scripts/fileuploaderextended.js /root/dokuwiki-2015-08-10a/lib/scripts/fileuploaderextended.js
diff -r dokuwiki/lib/scripts/hotkeys.js /root/dokuwiki-2015-08-10a/lib/scripts/hotkeys.js
diff -r dokuwiki/lib/scripts/jquery/jquery.js /root/dokuwiki-2015-08-10a/lib/scripts/jquery/jquery.js
diff -r dokuwiki/lib/scripts/jquery/jquery.min.js /root/dokuwiki-2015-08-10a/lib/scripts/jquery/jquery.min.js
diff -r dokuwiki/lib/scripts/jquery/jquery-ui.js /root/dokuwiki-2015-08-10a/lib/scripts/jquery/jquery-ui.js
diff -r dokuwiki/lib/scripts/jquery/jquery-ui.min.js /root/dokuwiki-2015-08-10a/lib/scripts/jquery/jquery-ui.min.js
diff -r dokuwiki/lib/scripts/jquery/jquery-ui-theme/smoothness.css /root/dokuwiki-2015-08-10a/lib/scripts/jquery/jquery-ui-theme/smoothness.css
diff -r dokuwiki/lib/scripts/jquery/update.sh /root/dokuwiki-2015-08-10a/lib/scripts/jquery/update.sh
diff -r dokuwiki/lib/scripts/linkwiz.js /root/dokuwiki-2015-08-10a/lib/scripts/linkwiz.js
diff -r dokuwiki/lib/scripts/locktimer.js /root/dokuwiki-2015-08-10a/lib/scripts/locktimer.js
diff -r dokuwiki/lib/scripts/media.js /root/dokuwiki-2015-08-10a/lib/scripts/media.js
diff -r dokuwiki/lib/scripts/page.js /root/dokuwiki-2015-08-10a/lib/scripts/page.js
diff -r dokuwiki/lib/scripts/toolbar.js /root/dokuwiki-2015-08-10a/lib/scripts/toolbar.js
diff -r dokuwiki/lib/tpl/dokuwiki/css/_admin.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_admin.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/basic.less /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/basic.less
diff -r dokuwiki/lib/tpl/dokuwiki/css/content.less /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/content.less
diff -r dokuwiki/lib/tpl/dokuwiki/css/design.less /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/design.less
diff -r dokuwiki/lib/tpl/dokuwiki/css/_edit.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_edit.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/_forms.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_forms.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/_links.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_links.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/_media_fullscreen.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_media_fullscreen.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/_media_popup.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_media_popup.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/mobile.less /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/mobile.less
diff -r dokuwiki/lib/tpl/dokuwiki/css/_modal.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/_modal.css
diff -r dokuwiki/lib/tpl/dokuwiki/css/pagetools.less /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/pagetools.less
diff -r dokuwiki/lib/tpl/dokuwiki/css/print.css /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/css/print.css
diff -r dokuwiki/lib/tpl/dokuwiki/detail.php /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/detail.php
diff -r dokuwiki/lib/tpl/dokuwiki/images/pagetools-build.php /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/images/pagetools-build.php
diff -r dokuwiki/lib/tpl/dokuwiki/main.php /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/main.php
diff -r dokuwiki/lib/tpl/dokuwiki/mediamanager.php /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/mediamanager.php
diff -r dokuwiki/lib/tpl/dokuwiki/template.info.txt /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/template.info.txt
diff -r dokuwiki/lib/tpl/dokuwiki/tpl_header.php /root/dokuwiki-2015-08-10a/lib/tpl/dokuwiki/tpl_header.php



At this point I'm not sure what happened. I edited the inc/init.php to be able to use the dokuwiki. As I am not a complete dokuwiki expert, I cannot say if these are all the changes. Either the upgrade plugin jumped over a version which introduced vendor  (however it demanded write access on vendor) or something strange was going on during update (maybe file permission check or error handling).

**Comment by splitbrain** [comment] 2015-09-29 14:47
Can you try running the upgrade plugin again?

**Comment by aw-systems** [comment] 2015-09-29 15:18
I edited the version and reset it to some 2014-08-10a "Test", update was performing as previously, this time it worked. /vendor is there, autoload.php is there and everything seems to work.

**Comment by thomaspahl** [comment] 2016-01-25 17:46
I could reproduce the problem on a small webhosting account, repeatedly, upgrading Hrun-d to Detritus-a. Obviously, a number of files (and directories) were missing after update (mostly in the new vendor/ tree). No problem occurred doing the same on a fast local server. My guess would be that the update script hits max execution time, but I could not find a corresponding error in the Apache logs yet. Webhost runs php5.4, my local one php5.6. Original installation was plain Hrun (no manual symlinks etc.).

Creating a dummy vendor/autoload.php made the front end run again, but not the backend. Re-running the update won't work ("client denied by server configuration" for whatever reason). Finally restored the wiki from my local copy. I still have the damaged wiki, may be I'll find time to analyze it further.

**Comment by zadl** [comment] 2016-06-09 11:37
I am facing the missing vendor/autoload.php file on any fresh installed Fedora 23/24beta system.

/etc/httpd/logs/error_log says:
PHP Fatal error:  require_once(): Failed opening required '/usr/share/dokuwiki/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/dokuwiki/inc/init.php on line 194

Commenting out line 194 works for me and the blank screen is gone.

**Comment by pstieber** [comment] 2016-06-23 03:22
I just upgrades a working Fedora 23 system to Fedora 24 and hit the same problem. As ghost stated, commenting like 194 of ```/usr/share/dokuwiki/inc/init.php``` fixed the problem.

**Comment by rasos** [comment] 2016-06-28 14:24
I just upgraded manually (overwrite tar) from Binky to Elenor of Tsort on Ubuntu 14.04 and I can confirm, that commenting out the autoload.php solved the problem of the blank screen as well here.

**Comment by splitbrain** [comment] 2016-06-28 14:35
Guys, commenting out the autoloader will **not** fix any problems. It might seem to work, but will break later at various places.

If your installation does not have a vendor directory, something went wrong with the upgrade.

The official downloads do have a vendor directory. When the upgrade plugin does not work for you, do a manual upgrade.

**Comment by rathann** [comment] 2016-09-15 10:56
@ghost, @pstieber, it looks like this was reported in Fedora bugzilla already: https://bugzilla.redhat.com/show_bug.cgi?id=1372948

**Comment by splitbrain** [comment] 2017-03-02 15:57
closing this as it seems fedora specific

**Closed by splitbrain** 2017-03-02 15:57 UTC
