### ISSUE TITLE
Upgrade plugin is offering RC candidates rather than "stable" or hotfixes.

### ISSUE THREAD

**Issue by PresGas** [splitbrain/dokuwiki-plugin-upgrade#195] opened 2020-07-03 13:28 UTC
My current installation is not offering the stable hotfix version of "Greebo", but the release candidate for "Hogfather"

>  DokuWiki rc-2020-06-09 "Hogfather" RC3 is available for download.
You're currently running DokuWiki Release 2018-04-22b "Greebo".

Is there a way for the plugin to work as per the summary of the Usage section?
https://www.dokuwiki.org/plugin:upgrade#usage

I upgraded the plugin before performing the wiki upgrade:

> Installed version:
>     2020-06-03
> Your last update:
>     Fri, 03 Jul 2020 13:15:37 +0000

**Comment by splitbrain** [comment] 2020-07-04 08:18
duplicate of #189

**Closed by splitbrain** 2020-07-04 08:18 UTC
