### ISSUE TITLE
choosing release candidate instead of last stable

### ISSUE THREAD

**Issue by Spockie** [splitbrain/dokuwiki-plugin-upgrade#189] opened 2020-06-02 12:31 UTC
Currently, the upgrade plugin only allows installation of the RC "Hogfather", but not the hotfix for Greebo. I think that this plugin should not be meant for updating to "beta" versions.

Dokuwiki has this message for admin:
New release candidate available: 2020-06-01 "Hogfather". upgrade now! [51] (what's this?)
Hotfix release available: 2018-04-22c "Greebo". upgrade now! [50.3] (what's this?)

But Wiki Upgrade extension is saying:
 DokuWiki rc2020-06-01 "Hogfather" is available for download.
 You're currently running DokuWiki Release 2018-04-22b "Greebo".

**Comment by rellampec** [comment] 2020-06-02 23:09
**aside note:** when you choose Hogfather, it recommends to do a manual install because, even though it know you are on `Greebo`, it says that cannot recognise your version!

**Comment by nipuli** [comment] 2020-06-04 12:12
I trapped into exactly the same issue as Spockie: I was not aware, that the only announced possibility to upgrade to (there was no choice in the upgrade plugin) will install a release candidate. It would have been great being able to chose.

Unfortunaltely Hogfather-RC1 breaks if bootstrap3-template ([bootstrap3/issues](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues)) or latex-plugin is installed. Which you recognize **after** the upgrade.

A revert to Greebo--22c would be great in the meantime. Maybe some suggestions?

**Comment by helgator** [comment] 2020-06-08 11:11
> Unfortunaltely Hogfather-RC1 breaks if bootstrap3-template ([bootstrap3/issues](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues)) or latex-plugin is installed. Which you recognize **after** the upgrade.

I can confirm that Hogfather breaks the bootstrap3-template and the ability to set the update plugin to Greebo is a necessity.

**Comment by nipuli** [comment] 2020-06-10 10:29
Today, four announcements

- New release candidate 3 available: 2020-06-09 "Hogfather". upgrade now! [51.2] (what's this?)
- New release candidate 2 available: 2020-06-01 "Hogfather". upgrade now! [51.1] (what's this?)
- New release candidate available: 2020-06-01 "Hogfather". upgrade now! [51] (what's this?)
- Hotfix release available: 2018-04-22c "Greebo". upgrade now! [50.3] (what's this?)

But still no choice, would get Hogfather-RC3. 
But I want stable Greebo-22c, please, at first (at least, until the issues with plugins/templates are solved properly).

Please?

**Comment by nurupo** [comment] 2020-06-19 18:47
Yeah, updating to a RC version instead of the latest stable version is not what I want the upgrade plugin to do. Preferably you should be able to specify which version to upgrade to, but getting just the latest stable might be a good start.

**Comment by Marx1st** [comment] 2020-06-30 11:39
Any news on this? I really would like to update our Dokuwiki instance...

**Comment by splitbrain** [comment] 2020-06-30 12:53
Short answer: won't fix

Long answer: the way we currently handle RC releases in git and how the plugin works make this non-trivial to implement. You can always do manual upgrades or simply wait until the release you want is available. If somebody wants to invest the time needed to implemented this feel free to open a PR. Until then I'm closing this.

**Closed by splitbrain** 2020-06-30 12:53 UTC
