### ISSUE TITLE
Request reader with duplicate server_name

### ISSUE THREAD

**Issue by ghost** [splitbrain/dokuwiki-plugin-upgrade#199] opened 2020-08-06 03:32 UTC
Hey, Andreas! Thanks for this plugin. I used it just now to perform an upgrade and something weird happen.

When I try to access the dokuwiki default page, the url is like this:

**URL ENTERED:** _http://wiki.domain.com_
**URL RETURNED:** _http://wiki.domain.com/wiki.domain.com/doku.php_

The page itself is working fine and when I access another area like "Admin" the url goes back to normal (http://wiki.domain.com/doku.php?id=start&do=admin)

I´ve checked all my nginx configs and doesn´t seem to bem anything off. 
**My .conf file is as follows:**

_server {
    listen [::]:80;
    listen 80;

    server_name wiki.domain.com; # Replace with your hostname
    root /var/www/dokuwiki;
    index index.html index.htm index.php doku.php;

    client_max_body_size 10M;
    client_body_buffer_size 128K;

    location ~ /(data/|conf/|bin/|inc/|install.php) { deny all; }

    location / {
        try_files $uri $uri/ @dokuwiki;
    }

    location ^~ /conf/ { return 403; }
    location ^~ /data/ { return 403; }
    location ~ /\.ht { deny all; }

        location @dokuwiki {
        # rewrites "doku.php/" out of the URLs if you set the userwrite setting to .htaccess in dokuwiki config page
        rewrite ^/_media/(.*) /lib/exe/fetch.php?media=$1 last;
        rewrite ^/_detail/(.*) /lib/exe/detail.php?media=$1 last;
        rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
        rewrite ^/(.*) /doku.php?id=$1&$args last;
    }

    location ~ \.php$ {
        try_files $uri $uri/ /doku.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REDIRECT_STATUS 200;
    #    fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_pass 127.0.0.1:9000;
    }

}_

Any other ideas?

Thanks much!

**Comment by splitbrain** [comment] 2023-04-12 07:39
I don't see how this should be caused by the upgrade plugin unless you had modified your conf/dokuwiki.php instead of having all changed configuration in conf/local.php as recommended. Check your baseurl and basedir settings.

closing this as it's not upgrade plugin related.

**Closed by splitbrain** 2023-04-12 07:39 UTC
